server:
  port: 9005
spring:
  application:
    name: Obj Application
easy-es:
  enable: true # 默认为true,若为false时,则认为不启用本框架
  address: localhost:9200  #填你的es连接地址
  username: 1
  password: 1
logging:
  file:
    name: obj.log
  level:
    cc.orcl.obj.dao: debug
